# Generated by Django 3.2.8 on 2021-10-16 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('script_name', models.CharField(max_length=250)),
                ('target_price', models.IntegerField(default=0)),
                ('stop_loss', models.IntegerField(default=0)),
                ('holding_period', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField()),
                ('user_id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Stocks',
            },
        ),
    ]
