# Generated by Django 3.2.8 on 2021-10-24 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0004_alter_stocks_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexData',
            fields=[
                ('forex_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_code', models.CharField(max_length=5, null=None, unique=True)),
                ('currency_value', models.IntegerField(null=None)),
                ('currency_arrow', models.CharField(default='UP', max_length=5)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
