# Generated by Django 3.2.8 on 2021-10-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0005_forexdata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='forexdata',
            table='ForexData',
        ),
    ]
