# Generated by Django 3.2.8 on 2021-10-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0006_alter_forexdata_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forexdata',
            name='currency_value',
            field=models.FloatField(null=None),
        ),
    ]
