# Generated by Django 3.2.8 on 2021-10-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0007_alter_forexdata_currency_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forexdata',
            name='currency_value',
            field=models.CharField(max_length=250, null=None),
        ),
    ]
