# Generated by Django 3.2.9 on 2021-11-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0009_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_custom_id',
            field=models.CharField(blank=True, max_length=5000, unique=True),
        ),
    ]
