# Generated by Django 3.2.9 on 2021-11-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0011_rename_event_custom_id_event_event_id_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id_custom',
            field=models.CharField(max_length=5000, unique=True),
        ),
    ]
