# Generated by Django 3.2.9 on 2021-11-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0012_alter_event_event_id_custom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_id_custom',
            new_name='eventid_custom',
        ),
    ]
