# Generated by Django 3.2.9 on 2021-11-06 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0013_rename_event_id_custom_event_eventid_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventid_custom',
        ),
    ]
