# Generated by Django 3.2.9 on 2021-11-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0015_event_event_id_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_id_custom',
        ),
    ]
