# Generated by Django 3.2.9 on 2021-11-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0017_stocks_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='forexdata',
            name='rate_diff',
            field=models.CharField(default='0.0', max_length=250, null=None),
        ),
        migrations.AlterField(
            model_name='forexdata',
            name='currency_arrow',
            field=models.CharField(default='DEFAULT', max_length=10),
        ),
    ]
