# Generated by Django 3.2.9 on 2021-11-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0018_auto_20211107_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forexdata',
            name='currency_code',
            field=models.CharField(max_length=15, null=None, unique=True),
        ),
    ]
