# Generated by Django 3.2.9 on 2021-11-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0019_alter_forexdata_currency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
