# Generated by Django 3.2.9 on 2021-11-27 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0020_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_message', models.TextField()),
            ],
            options={
                'db_table': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('user_notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_id', models.ForeignKey(db_column='notification_id', on_delete=django.db.models.deletion.CASCADE, to='stock_app.notification')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
