# Generated by Django 3.2.9 on 2022-01-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0022_usernotification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_title', models.TextField()),
                ('news_link', models.TextField()),
            ],
            options={
                'db_table': 'News',
            },
        ),
    ]
